### ISSUE TITLE
Jira Status not found when multiple statuses with same name exist

### ISSUE THREAD

**Issue by Lvdagilis** [trendmicro/tm-v1-connectors#20]
Using the Jira connector, we are unable to map the Jira statuses to Vision One statuses The issue type specified in the config.yml contains a specific workflow with a few custom statuses. These statuses are added in the config.yml

The config.yml relevant section is below:
```
status:
  - name: Open
    inv: New
  - name: In Progress
    inv: In Progress
  - name: Resolved
    inv: Closed
```

We also have some fields required on transition for Resolved, and this is entered in the config, just hidden for privacy reasons from here.

We then get the following output when running app.py

`2024-07-31 16:12:34 INFO  ::: 12972 app.py             ::: _load_cache       :93    ::: App :::  Loaded cache: {}
2024-07-31 16:12:34 INFO  ::: 12972 core.py            ::: _send_internal    :243   ::: App :::  Sending request [Method=GET, URL=https://api.eu.xdr.trendmicro.com/v3.0/healthcheck/connectivity, Headers={'Authorization': '***** 'User-Agent': 'v1jira-PyTMV1/0.8.7'}, Body=None]
2024-07-31 16:12:35 INFO  ::: 12972 core.py            ::: _send_internal    :255   ::: App :::  Received response [Status=200, Headers={'Date': 'Wed, 31 Jul 2024 13:12:35 GMT', 'Content-Type': 'application/json', 'Content-Length': '22', 'Connection': 'keep-alive', 'x-trace-id': 'a9a3f64b-d813-4b73-8dae-fbb242263afc', 'x-task-id': '9a1164e8-9dd2-460b-8ec8-31b545f4bec0', 'TMV1-Customer-ID': 'redacted', 'strict-transport-security': 'max-age=31536000; includeSubDomains'}, Body={"status":"available"}]
2024-07-31 16:12:35 INFO  ::: 12972 app.py             ::: _check_conn       :294   ::: App :::  Successfully connected to Vision One and JIRA
2024-07-31 16:12:36 ERROR ::: 12972 app.py             ::: _validate_statuses:713   ::: App :::  JIRA Status mapping error
JIRA Status not found: ['Pending', 'In Progress', 'Resolved']`

Our JIRA statuses are in the attached .xslx, as exported from the Jira API. The statuses as can be seen obviously exist, so our guess is that there are multiple statuses with the same name and so mapping fails. Using the status ID instead of the name in the config.yaml doesn't work either.
[jirastatuses.xlsx](https://github.com/user-attachments/files/16442370/jirastatuses.xlsx)

**Comment by t0mz06** [comment]
Hello @Lvdagilis,

Thank you for reporting the issue,
Could I ask you to send me the debug logs please?

Please if you could try also with the latest version from the repository.

Regards,
Thomas.

**Comment by t0mz06** [comment]
Hi @Lvdagilis ,

We also upgraded to python 3.8 due to end of life support of python 3.7, please make sure that you are using >= python 3.8 and that pytmv1 package is upgraded (the requirements.txt file was updated)

Thank you very much,
Thomas.

**Comment by t0mz06** [comment]
Hello @Lvdagilis,

Just wanted to follow up with you if you were able to fix the issue or not?

Thank you,
Thomas.

**Comment by Lvdagilis** [comment]
Hey @t0mz06  - getting some progress. Made sure to update Python, package, and the requirements (though doesn't seem any new requirements were installed). 

Seems like I might just need some support to get this mapped properly now, getting a different error at this point:
Config fields not found: ['resolution']
Required fields missing: []

Attaching the debug info from the console (censored our domain and TM customer ID)
[tm debug.txt](https://github.com/user-attachments/files/16908323/tm.debug.txt)

**Comment by t0mz06** [comment]
Hello @Lvdagilis,

I think you can remove the resolution field from your configuration as it seems it is not present on your JIRA instance for the specific issue type, hence it is failing.

It should fix the problem.
Otherwise feel free to reach out on integrations@trendmicro.com and we can schedule a meeting to address this or anything else.

Thanks,
Thomas.

**Comment by AmbientPlatypus** [comment]
Possible fix offered. If any other assistance is necessary, contact
[integrations@trendmicro.com](mailto:integrations@trendmicro.com).

**Comment by AmbientPlatypus** [comment]
Possible fix offered. If any other assistance is necessary, contact
[integrations@trendmicro.com](mailto:integrations@trendmicro.com)
